### ISSUE TITLE
Typo in one of the tutorials

### ISSUE THREAD

**Issue by Pverheijen** [scailable/sclbl-tutorials#13]
Hey guys,

Minor type that might cause confusion.
Resulting output is 55 not 15 (code example and text difference).

https://github.com/scailable/sclbl-tutorials/tree/master/sclbl-create-your-own-wasm

**Comment by Pverheijen** [comment]
I've opened a pull request for it. 

https://github.com/scailable/sclbl-tutorials/pull/14

**Comment by robinvanemden** [comment]
> I've opened a pull request for it.
> 
> #14

Super, thanks!

**Comment by robinvanemden** [comment]
Merged #14 
Closes issue.
