### ISSUE TITLE
Just Another Dangerous Situation

### ISSUE THREAD

**Issue by koaning** [scailable/sclbl-tutorials#7]
There are many datasets out there that can be used to demonstrate how a cloud service works. The authors of this service chose to make a demo of a machine learning model that uses gender to predict a developers salary. The suggestion is made that it is okay to use a model to predict salaries, when that model does not account for pre-existing bias in any way. For a demo, which people will refer to as an authoritative source, that is irresponsible. Especially when this project is backed by folks who teach students how to do data science in an academic setting.

I've raised the issue on linkedin and there's a few things about the [conversation on linkedin](https://www.linkedin.com/feed/update/urn:li:activity:6679637058597789696/?commentUrn=urn%3Ali%3Acomment%3A(activity%3A6679637058597789696%2C6679704886969475072)&replyUrn=urn%3Ali%3Acomment%3A(activity%3A6679637058597789696%2C6679775009537343488)) that stand out to me;

- It was initially suggested that "we don't believe that [the gender pay gap] had a significant impact on the outcomes" while just checking the base example live on the website yields a $35K salary difference between men and women.
- It was initially suggested that placing a small disclaimer under the "additional information" is enough. This disclaimer mentioned "we duly apologize for the severe imbalance that was apparently picked up by the ML model". This disclaimer literally mentions that the imbalance is "apparently" a surprise to the authors. Combining this with the first observation makes me believe that this was considered that adding gender to a model might cause a bias in salary difference.
- The disclaimer was later amended when multiple people started pitching in. The first sentence of the new disclaimer reads "As anticipated before training this model, and some of our users also found, the salary data we used seems to exhibit a severe gender imbalance". The choice of words here boggles me. How can you say "seems to exhibit" when it a.) definitely is there and b.) when it is anticipated? 
- The disclaimer also mentions "Sometimes model deployment makes injustice painfully visible" and concludes with a suggestion that the reader needs to take responsibility and read an article. I fail to see how this statement is appropriate when the exact opposite applies. Applying a biased model is usually a painfully *in-visible* method of data-laundering pre-existing bias. In this demo the user is able to see the modes input but in a real-life application this information is typically invisible. Imagine that the column was not shown, then there'd still be features correlating with the bias and it would still be in the model.

I've shared the website as well as the linkedin discussion with my peers, some of which felt like pitching in but one comment sent to me in private stood out;
"It is hard to type a response when one hand is preoccupied with face-palming."

Respectfully, I find it worrisome that ethics were not properly considered in the design process. The response, frankly, amplifies my worries. It certainly did not help to read that a group of professionals consider that adding a small disclaimer is an acceptable remedy.

It is my understanding that there's a new version live of the demo so I figured I'd have a look. I just played with the new tool which now tries to address the imbalance by referring to "getraised.com". It turns out that the tool is now selective. When you select the "other" gender it does not mention how you can increase your wage. It also only compares you against the female salary (not the male one, which is higher).

![image](https://user-images.githubusercontent.com/1019791/85194158-bcde9e00-b2cc-11ea-8d85-4923c56def08.png)

I'm assuming this was not a conscious decision but it again demonstrates the wrong attitude of "let's add a patch and then the demo will be fine". The initial observation was about a salary difference but the underlying issue is that the team did not consider the consequences of applying this model. The result of this *attitude* is that now there's a patch for salary injustice between men and women without thinking of the salary gap with folks who do associate either category.

I suppose I have a lot of advice here but the main one is; be better. I fail to see why it is 100% necessary to use a controversial application as a demo of how you can deploy a machine learning model on a cloud platform. Heck, here's a nice dataset about [penguins](https://github.com/allisonhorst/palmerpenguins). Not only does it offer "not controversy", it will also make the demo notebook much simpler because it is a much simpler dataset. You can bring the focus back to your cloud service.

This is not the first time I had to point out an irresponsible demo to a data company but it is the first time that I had to do it to a group from an academic setting. Some of you are associated with academic institutions that teach data science to students and this is setting a bad example. Please think ahead about this sort of thing and educate yourself; it's not like there's no resources available.

- There's the [deon checklist](https://deon.drivendata.org/examples/).
- There's loads of pydata talks; here's [a relevant one](https://www.youtube.com/watch?v=m_KnKm0Tr4c) and [another one](https://www.youtube.com/watch?v=Z8MEFI7ZJlA). The latter video is especially relevant if any of you teach using the Boston housing dataset.
- There's even some [books](https://weaponsofmathdestructionbook.com/).

I've also had a look at the notebook that generates the model. I fail to understand why you'd want to choose XGBoost as a model here. It feels like this is an application where interpretability and understandability really matter, so why choose XGBoost? There's even an interesting quote in the notebook about the decision.

> So the performance of this model is still pretty poor; it should be relatively easy to improve. However, we move on to deployment anyway.

If it is relatively easy to improve, why haven't you?

**Comment by MKaptein** [comment]
Hi, thanks again for the discussion and the pointers to the literature on this issue. We decided to  take the app offline because we agree that it is not "100% necessary to use a controversial application for the demo". Frankly, it is not necessary at all and we should have been more careful. We will incorporate your comments into our future work.

We try to keep the git repo for bugs and feature requests. However, shall I leave this issue open to make sure visitors can read the discussion? I would also be happy to organize a discussion on the topic / move the resources you provided elsewhere. Looking forward to hearing your thoughts.

**Comment by MKaptein** [comment]
Given inactivity on this issue, I will close it for now.
